#include <iostream>
#include <string>

int displayQuiz(std::string questions[], std::string options[][4], char answersKey[], int size){
    char guess = 0;
    int score = 0;

    for (int i = 0; i < size; i++)
    {
        std::cout << questions[i] << '\n';
        std::cout << "--------------------------------------------------------------------------------------------------------------------------------------------------------\n";

        for (int j = 0; j < sizeof(options[i]) / sizeof(options[i][0]); j++)
        {
            std::cout << options[i][j] << '\n';
        }

        std::cin >> guess;
        guess = toupper(guess);

        if (guess == answersKey[i])
        {
            std::cout << "Correct!\n"
                      << '\n';
            score++;
        }
        else
        {
            std::cout << "Incorrect!\n";
            std::cout << "Answer: " << answersKey[i] << '\n'
                      << '\n';
        }
    }

    return score;
}

void displayResults(int score, int size){
    std::cout << "========================================================================================================================================================\n";
    std::cout << "Results\n";
    std::cout << "========================================================================================================================================================\n";

    std::cout << "Correct Guesses: " << score << '\n';
    std::cout << "# of questions: " << size << '\n';
    std::cout << "Score: " << (score/(double)size)*100 << "%\n";
}

int main()
{

    std::string questions[] = {
        "What primary mechanism prevents a main-sequence star from collapsing under its own immense gravitational force?: ",
        "The apparent brightness of a star decreases with distance according to which mathematical relationship?",
        "Which boundary defines the radius around a black hole where the escape velocity exactly equals the speed of light?: ",
        "When observing a distant galaxy, its spectral lines are shifted toward longer wavelengths. What does this Cosmological Redshift indicate?: ",
        "What property of a Cepheid variable star makes it an invaluable 'standard candle' for measuring cosmic distances?: "};

    std::string options[][4] = {
        {"A. Hydrostatic equilibrium created by outward thermal radiation pressure from core fusion.",
         "B. The centrifugal force generated by the rapid rotation of the stellar core.",
         "C. Electron degeneracy pressure within the outer convective zones.",
         "D. The string nuclear force acting as a long-range repulsive interaction between nucleos."},
        {"A. An inverse-cubic law, where brightness is proportional to 1/d^3.",
         "B. An exponential decay law, where brigthness decreases by a fixed percentage per parsec.",
         "C. An inverse-square law, where brightness is proportional to 1/d^2.",
         "D. A Linear relationship, where brigthness is proportional to 1/d."},
        {"A. The Roche limit.",
         "B. The event horizon.",
         "C. The accretion disk boundary.",
         "D. The gravitational singularity."},
        {"A. The space between galaxy and observer is expanding.",
         "B. The galaxy is moving through stationary space toward the observer.",
         "C. The star systems within that galaxy are cooling down and emitting lower-energy photons.",
         "D. The galaxy's core is undergoing rapid gravitational collapse into a supermassive black hole."},
        {"A. Its precise, invariant rotational period which acts as a cosmic pulsar.",
         "B. The constant, unchanging velocity ay which it moves through its host galaxy.",
         "C. Its uniform chemical composition, consisting entirely of primordial hydrogen and helium.",
         "D. The direct relationship between it pulsation period and its intrinsic luminosity."}};

    char answersKey[] = {'A', 'C', 'B', 'A', 'D'};
    int size = sizeof(questions) / sizeof(questions[0]);

    std::cout << "========================================================================================================================================================\n";
    std::cout << "Welcome to the AstroPhysics quiz!!!!\n";
    std::cout << "========================================================================================================================================================\n";

    int score = displayQuiz(questions, options, answersKey, size);

    displayResults(score, size);

    return 0;
}